チャットルームのER図を作成
ytaka0407/quelcode-db pull request #1
Opened 2020-11-23 15:48 UTC by ytaka0407

2020-11-23 16:45 UTC, choimake reviewed
拝見しました。
中間テーブルの存在が、ER図に入っている点がgoodです。

いくつか気になった点があり、以下に記載していますので、確認の上対応お願いします。

- ログインテーブルは不要
本課題のようなWeb系のサービスにおいては、ログイン情報はSessionに入れるケースが主です。
よって今回のようにログインテーブルを作らずともSession機能を使えばログイン機能は実装できるので、ログインテーブルは消して大丈夫だと思います。

- 会員登録行為と利用者情報というテーブルはひとつにできるのでは？
要件をみるに、この2つ合わせてひとつのユーザー関連機能とみなすことができるので、特に分ける必要性がないようにみえます。

- 論理削除にアカウント有効化やタスク有効化などの名前が振られているが、これは論理削除のままでよいかと
論理削除とはデータの削除の方法のひとつでデータが削除されたかどうかを管理するためのものです。物理削除と対になります。
そして論理削除そのものには有効化みたいな意味はありませんので、論理削除のままでよいと思います。
（もし有効化を管理したいなら、専用のカラムを別で作ります）

参考
https://qiita.com/jonson29/items/4743409eda08fcdf5410

- チャットルーム参加状況のテーブルに退出時間というカラムがあるが、これは不要では？
「退出時間が分かるように」という要件はないので、このカラムは消して大丈夫です。
要件外のものは実装しないようにしましょう。
（もし追加したいということであれば、要件を変更してもらうようにしてください。これは実務においてもそうです。）

- チャットルーム参加状況というテーブルは、利用者情報というテーブルとチャットルームの中間テーブルなので複数主キーになるのでは？
これに関しては一旦ご自分で調べてみてください。

- チャットルームに作成者、更新者、作成時間、更新時間がない
上記の通りです。

- 投稿内容テーブルに更新日時が2つあります

2020-11-25 08:05 UTC, ytaka0407 commented
お疲れ様です。
ご指摘いただいた点を修正しました。
ご確認よろしくお願いいたします。

・ログインテーブルは不要
→sessionで十分な点、理解しました。テーブルごと削除しました。

・会員登録行為と利用者情報というテーブルはひとつにできるのでは？
→会員登録テーブルを削除し、代わりに利用者情報に登録日時のカラムを追加しました。

・論理削除にアカウント有効化やタスク有効化などの名前が振られているが、これは論理削除のままでよいかと
→参考サイトありがとうございます。カラム名を「論理削除」で統一しました。

・チャットルーム参加状況のテーブルに退出時間というカラムがあるが、これは不要では？
→要件を再度確認し、退出時間カラムを削除しました。

・チャットルーム参加状況というテーブルは、利用者情報というテーブルとチャットルームの中間テーブルなので複数主キーになるのでは？
→複合主キーについて再度確認しました。
今回、参加時間カラムは複合主キー全体に従属しているので、利用者id+チャットルームidで複合主キーに設定しました。

チャットルームに作成者、更新者、作成時間、更新時間がない
→すみません、ケアレスミスです。カラム追加しました。

投稿内容テーブルに更新日時が2つあります
→ケアレスミスでした。重複しているカラム削除しました。

2020-11-25 13:14 UTC, piasoratech requested changes
以下の内容について確認をお願いします。

- チャットルームに作成者のカラムがありません。
- 投稿内容のテーブルにある「利用者id」は投稿者のidでしょうか？意味を考えると命名がずれているように感じるので直しておいてください。
- 投稿内容のテーブルで「投稿日」に対して「更新日時」となっているので日時の方に統一しましょう。(細かい話ですが、プログラムで〇〇日と〇〇日時は違う種別と判断することが多いので気をつけて見てください。)
- 要件にも記載の通り「1つのタスクは1つのチャットルームに紐づく」のでリレーションをもう一度見直しましょう。
- これも細かい話になってしまうのですが、一般的に「作成者、更新者、作成日時、更新日時」は順序的に各テーブルの一番下の項目になるようにします。今の状態だとFKを意識して上の項目になっているものがあるので、確認してみてください。
- 全体的なリレーションのカーディナリティも少し確認してみましょう。このサイトが参考になるかと思います。 (https://it-koala.com/entity-relationship-diagram-1897) ちょっと難易度が高いのでできたらで大丈夫です。

2020-11-26 08:54 UTC, ytaka0407 commented
チャットルームに作成者のカラムがありません。
→一度で直っておらず申し訳ございません。修正しました。

投稿内容のテーブルにある「利用者id」は投稿者のidでしょうか？意味を考えると命名がずれているように感じるので直しておいてください。
→ご指摘のカラム含め、各テーブルの名称を見直しました。

投稿内容のテーブルで「投稿日」に対して「更新日時」となっているので日時の方に統一しましょう。(細かい話ですが、プログラムで〇〇日と〇〇日時は違う種別と判断することが多いので気をつけて見てください。)
→修正しました。表記方法について今後意識していきます。

要件にも記載の通り「1つのタスクは1つのチャットルームに紐づく」のでリレーションをもう一度見直しましょう。
→要件を見落としておりました。見直しし、カラムおよびリレーションを修正しました。

これも細かい話になってしまうのですが、一般的に「作成者、更新者、作成日時、更新日時」は順序的に各テーブルの一番下の項目になるようにします。今の状態だとFKを意識して上の項目になっているものがあるので、確認してみてください。
→見直しし、並び替えました。(すみません、この部分ほかの修正と分割せずにコミットしてしまいコメントが残せていません。)

全体的なリレーションのカーディナリティも少し確認してみましょう。このサイトが参考になるかと思います。 (https://it-koala.com/entity-relationship-diagram-1897) ちょっと難易度が高いのでできたらで大丈夫です。
→リンク先の記事で記述方法再確認しました。
チャットルームとチャットルーム参加状況のリレーションを、1対0以上から1対1以上に変更しました。他、要件に沿って選んだつもりなのですが、誤りがありましたらお手数ですがコメント頂けると幸いです。

2020-11-26 16:16 UTC, gacha1987 commented
- チャットルームテーブル.チャットルームidと利用者情報.利用者idは`(PK/FK)`となっていますが、どちらもテーブルにとっては外部キーではないのでFKの表記は不要です。

- チャットルームテーブルの「参加時間」カラムは他の時間系のカラム名と合わせるなら「参加日時」の方が適切と思います。

- タスクテーブルの更新者idは下記の指摘に合わせるならば下の方に持っていった方が良いです。また、カラムの順番として論理削除が一番下に来ており、「作成者、更新者、作成日時、更新日時」が一番下に来ていないのでこちらも併せて修正してください。
>これも細かい話になってしまうのですが、一般的に「作成者、更新者、作成日時、更新日時」は順序的に各テーブルの一番下の項目になるようにします。今の状態だとFKを意識して上の項目になっているものがあるので、確認してみてください。
→見直しし、並び替えました。(すみません、この部分ほかの修正と分割せずにコミットしてしまいコメントが残せていません。)

- タスクテーブルのみ更新者idと作成者idに`(FK)`が記載されており、他のテーブルの更新者idと作成者idには記載がありませんので統一しましょう。

2020-11-28 03:27 UTC, ytaka0407 commented
・チャットルームテーブル.チャットルームidと利用者情報.利用者idは(PK/FK)となっていますが、どちらもテーブルにとっては外部キーではないのでFKの表記は不要です。
→FKを誤って認識していました。外部のデータを必要とする側が(利用者テーブルと接続しないと情報が不完全なもの)FK、その情報を提供する側はFKではないと理解しました。(接続しうるキーを全部いっしょくたにFKにしておりました。。)

・チャットルームテーブルの「参加時間」カラムは他の時間系のカラム名と合わせるなら「参加日時」の方が適切と思います。
→統一しました。

・タスクテーブルの更新者idは下記の指摘に合わせるならば下の方に持っていった方が良いです。また、カラムの順番として論理削除が一番下に来ており、「作成者、更新者、作成日時、更新日時」が一番下に来ていないのでこちらも併せて修正してください。
→全体を見直しました。投稿内容の投稿者idも併せて動かしたのですが、これは適切でしょうか。
(作成者idに近いとは思うのですが、投稿内容においての投稿者idはほかのものに比べて重要度が高いので下にまとめるべきか迷いました。)

・タスクテーブルのみ更新者idと作成者idに(FK)が記載されており、他のテーブルの更新者idと作成者idには記載がありませんので統一しましょう。
→全体でFKに当たる部分すべてにFK表記を追加しました。

2020-11-28 06:25 UTC, choimake approved these changes
対応ありがとうございました。
LGTMです。

2020-11-28 14:57 UTC, merged