Db challenge3-3
ytaka0407/quelcode-db pull request #6
Opened 2020-12-11 14:28 UTC by ytaka0407

db課題3‐011～014のSQL文を作成・実行しました。

2020-12-11 15:15 UTC, piasoratech requested changes
コメントしたので確認をお願いします

2020-12-11 15:15 UTC, piasoratech commented on db/db-challenge3/db-011/db-11.sql
> +WHERE
更新日時が更新されていないです。

2020-12-11 15:15 UTC, piasoratech commented on db/db-challenge3/db-011/db-11.sql
> +    AND is_deleted = 0,
,はいらないです

2020-12-11 15:15 UTC, piasoratech commented on db/db-challenge3/db-012/db-12.sql
> +WHERE
更新日時が更新されていないです

2020-12-11 15:15 UTC, piasoratech commented on db/db-challenge3/db-013/cb-13.sql
> +WHERE
更新日時が更新されていないです

2020-12-11 15:15 UTC, piasoratech commented on db/db-challenge3/db-014/db-14.sql
> +DROP TABLE chat_rooms_joined_list;
要件が満たせていないです。
確認をしてみてください

2020-12-11 15:39 UTC, ytaka0407 commented on db/db-challenge3/db-011/db-11.sql
> +WHERE
回答ありがとうございました。問題ないとのことでしたのでupdate current_timestampで更新のままです。

2020-12-11 15:39 UTC, ytaka0407 commented on db/db-challenge3/db-011/db-11.sql
> +    AND is_deleted = 0,
修正完了しました。

2020-12-11 15:39 UTC, ytaka0407 commented on db/db-challenge3/db-012/db-12.sql
> +WHERE
回答ありがとうございました。問題ないとのことでしたのでupdate current_timestampで更新のままです。

2020-12-11 15:39 UTC, ytaka0407 commented on db/db-challenge3/db-013/cb-13.sql
> +WHERE
回答ありがとうございました。問題ないとのことでしたのでupdate current_timestampで更新のままです。

2020-12-11 15:40 UTC, ytaka0407 commented on db/db-challenge3/db-014/db-14.sql
> +DROP TABLE chat_rooms_joined_list;
大幅に見落としておりました。
再度作成、実行キャプチャ上書きしました。

2020-12-12 03:52 UTC, choimake reviewed
db-11のみ確認してみましたが、記載のSQLを実行するとエラーが発生しました。

動作できる状態のSQLに修正した上で再度提出してください。

2020-12-12 13:13 UTC, gacha1987 commented
LGTMです。

2020-12-13 00:20 UTC, merged